#!/bin/bash

GROUP="$1"
shift
if [ $(getent group "$GROUP") ]; then
   exit 1
fi

SETID="$1"
shift
groupadd -g $SETID "$GROUP"
IFS=','
gpasswd -M "$*" "$GROUP"

DATA="/nfs/$GROUP-data"
if [ ! -d "$DATA" ]; then
    mkdir "$DATA"
    chgrp "$GROUP" "$DATA"
    chmod g+swrx,o-rx "$DATA"
fi    
