#!/bin/bash

USER="$1"
if [ $(id "$USER") ]; then
   exit 1
fi

if [ "$#" -gt 1 ]; then
    PASS="$2"
else
    PASS="$USER"
fi

if [ "$#" -gt 2 ]; then
    SETID="$3"
fi

if [ -d "/home/$USER" ]; then
    useradd -p $(openssl passwd -1 $PASS) -u $SETID --no-create-home --home-dir "/home/$USER" $USER
else
    useradd -p $(openssl passwd -1 $PASS) $USER
    PGPASS="/home/$USER/.pgpass"
    echo "localhost:*:*:$USER:$PASS" > $PGPASS
    chmod 0600 $PGPASS
    chown $USER:$USER $PGPASS
    su - postgres -c "createuser --role=student $USER"
fi
